version: 2.1
parameters:
  version:
    type: string
    default: "latest"
orbs:
  github-cli: circleci/github-cli@1.0.4
  docker: circleci/docker@1.7.0
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build-job:
    docker:
      - image: pvmm/sdcc:latest
    environment:
      VERSION: << pipeline.parameters.version >>
    working_directory: /root/Mines
    steps:
      - checkout
      - run: cd platforms/msx2 && make
      - run: mkdir -p /root/Mines/minesweeper/msx2
      - run: cp platforms/msx2/build/minesweeper.rom /root/Mines/minesweeper/msx2
#      - run: cd platforms/gunsmoke && make
#      - run: mkdir -p /root/Mines/minesweeper/gunsmoke
#      - run: cp platforms/gunsmoke/build/3.ic85 /root/Mines/minesweeper/gunsmoke
#      - run: cp platforms/gunsmoke/build/gs03.09n /root/Mines/minesweeper/gunsmoke
#      - run: cp platforms/gunsmoke/build/gs01.11f /root/Mines/minesweeper/gunsmoke
      - persist_to_workspace:
          root: ./minesweeper
          paths: 
            - ./*

  deploy-job:
    docker:
     - image: cimg/base:stable

    steps:
      - github-cli/setup:
          version: 2.0.0
      - github-cli/clone:
          repo: $CIRCLE_REPOSITORY_URL
      - attach_workspace:
          at: ./minesweeper
      - run: gh release delete latest -y --repo $CIRCLE_REPOSITORY_URL || true
      - run: zip -r minesweeper.zip ./minesweeper/*
      - run: gh release create latest minesweeper.zip --repo $CIRCLE_REPOSITORY_URL

workflows:
  build-deploy-workflow:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job

